# -*- coding: utf-8 -*-
"""Final_Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t-yPE2xFi1CA56OdEbZNpJhm5BvtKQz-
"""

name = str(input("Ad Soyad bilgilerinizi giriniz: "))
print(f'Sayın {name.title()} Bilgi Yarışmasına Hoşgeldiniz')

#print(input("Ad Soyad bilgilerinizi giriniz: "))
#print("Merhaba name.title()
questions= {"Soru1: Türkiye'nin başkenti neresidir?"                                                  : "Ankara", 
            "Soru2: Dünya'nın uydusunun adı nedir?"                                                   : "Ay", 
            "Soru3: Güneş Sistemi'ndeki en büyük gezegenin adı nedir?"                                : "Jüpiter",
            "Soru4: İstiklal Marşı'nın şairi kimdir?"                                                 : "Mehmet Akif Ersoy",
            "Soru5: Türkiye'nin en büyük yüz ölçümüne sahip şehri hangisidir?"                        : "Konya", 
            "Soru6: Bozkırın tezenesi lakaplı rahmetli halk ozanı kimdir?"                            : "Neşet Ertaş",
            "Soru7: Uçaklarda pilot kabinine ne ad verilir?"                                          : "Kokpit",
            "Soru8: Yerden fışkırarak çıkan sıcak su kaynaklarına ne denir?"                          : "Gayzer",
            "Soru9: Gezilerini ‘Seyahatname’ adlı eserde toplayan Türk gezgin kimdir?"                : "Evliya Çelebi", 
            "Soru10: Osmanlı Devletinin kurucusu olan Osmanlı ailesi hangi Türk boyuna mensuptur?"    : "Kayı"}


questions_list=[]
answers_list=[]


for i,j in questions.items():
  questions_list.append(i)
  answers_list.append(j)
                       
#print(questions_list)
#print(answers_list)

score = 0.0

for i in range(0,len(questions_list)):
  answer= str (input("{}".format(questions_list[i])))

  

  if answer.title() == answers_list[i]:
    score += 10
    print("Doğru")

  else:
    print("Yanlış")
    
  
  i+=1

if score>50:
  print(f'KAZANDINIZ.\nPuan: {score}')
 # print("Pardus\nUbuntu")


else: 
  print(f'KAYBETTİNİZ.\nPuan: {score}')