# -*- coding: utf-8 -*-
"""Homework1_v2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15EupH7CyX9UxaFDCkQ5bTZpkMoLewe3x
"""

Number = int(input("Lütfen tek ve çift olarak sıralanmasını istediğiniz sınır değerini giriniz: "))

odd_numbers=[i for i in range(0, Number+1) if i % 2 == 1]
even_numbers=[i for i in range(0,Number+1) if i % 2 == 0]
new_list= odd_numbers + even_numbers
new_list.sort()
double_list= [i*2 for i in new_list]

print("Odd Numbers: ",odd_numbers)
print("Even Numbers: ",even_numbers)
print("New List: ",new_list)
print("Double List: ",double_list)

#print(f'Odd Numbers up to {Number}: ', odd_numbers)
#print(f'Even Numbers up to {Number}: ', even_numbers)
#print("Even Numbers: ",even_numbers)
#print(f'Numbers up to {Number}: ',new_list)
#print("Double List: ",double_list)

i=0
while (i < len(double_list)):
  print (i, "th item's type: ", type (double_list[i]))
  i += 1