# -*- coding: utf-8 -*-
"""Homework1_v1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/197p50JNuxhBOhrQgS52Z79JcC2ho_xAn
"""

Number = int(input("Lütfen tek ve çift olarak sıralanmasını istediğiniz sınır değerini giriniz: "))

odd_numbers=[i for i in range(0, Number+1) if i % 2 == 1]
even_numbers=[i for i in range(0,Number+1) if i % 2 == 0]
new_list= odd_numbers + even_numbers
#new_list.sort()
double_list= [i*2 for i in new_list]

print(f'Odd Numbers up to {Number}: ', odd_numbers)
print(f'Even Numbers up to {Number}: ', even_numbers)
print(f'Odd and Even Numbers up to {Number}: ',new_list)
print("Double List: ",double_list)

for i in range(0,len(double_list)):
  print (i, "th item's type: ", type (double_list[i]))