# -*- coding: utf-8 -*-
"""Homework1_v3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xNcMzdn5c51wCbXwuW-bUGufrmMwtbfk
"""

odd_numbers=[i for i in range(10) if i % 2 == 1]
even_numbers=[i for i in range(10) if i % 2 == 0]
new_list= odd_numbers + even_numbers
#new_list.sort()
double_list= [i*2 for i in new_list]
print("Odd Numbers: ",odd_numbers)
print("Even Numbers: ",even_numbers)
print("New List: ",new_list)
print("Double List: ",double_list)
i=0
while (i < len(double_list)):
  print(i, "th item's type: " , type (double_list[i]))
  i += 1