# -*- coding: utf-8 -*-
"""Homework3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qBBeveHbY0HbFV1uWiBx7eZqbA9XYTvC
"""

students = {"Ali Türk"    : {"Fakülte"           : "Fen Fakültesi",
                              "Öğrenci Numarası"  : 162200066,
                              "Bölüm"             : "Fizik",
                              "Yaş"               : 19,
                              "Vize Notu"         : 0.0,
                              "Proje Notu"        : 0.0,
                              "Final Notu"        : 0.0,
                              "Başarı Notu"       : 0.0},
              

           "Ayşe Akın"     : {"Fakülte"           : "Fen Fakültesi",
                              "Öğrenci Numarası"  : 162200067,
                              "Bölüm"             : "Fizik",
                              "Yaş"               : 20,
                              "Vize Notu"         : 0.0,
                              "Proje Notu"        : 0.0,
                              "Final Notu"        : 0.0,
                              "Başarı Notu"       : 0.0},
              
           
           "Efe Cantürk"   : {"Fakülte"           : "Fen Fakültesi",
                              "Öğrenci Numarası"  : 162200068,
                              "Bölüm"             : "Fizik",
                              "Yaş"               : 18,
                              "Vize Notu"         : 0.0,
                              "Proje Notu"        : 0.0,
                              "Final Notu"        : 0.0,
                              "Başarı Notu"       : 0.0},
              
           
          "Ezgi Sağlam"   : {"Fakülte"           : "Fen Fakültesi",
                             "Öğrenci Numarası"  : 162200069,
                             "Bölüm"             : "Fizik",
                             "Yaş"               : 22,
                             "Vize Notu"         : 0.0,
                             "Proje Notu"        : 0.0,
                             "Final Notu"        : 0.0,
                             "Başarı Notu"       : 0.0},
              
           
           "Oya Atasoy"    : {"Fakülte"           : "Fen Fakültesi",
                              "Öğrenci Numarası"  : 162200070,
                              "Bölüm"             : "Fizik",
                              "Yaş"               : 21,
                              "Vize Notu"         : 0.0,
                              "Proje Notu"        : 0.0,
                              "Final Notu"        : 0.0,
                              "Başarı Notu"       : 0.0}}
                            

students_list=[]
grades=["Vize Notu","Proje Notu","Final Notu"]
percents=[0.3,0.3,0.4]
passing_grade=[]

for i in students.keys():
  students_list.append(i)

#print(students)

for i in range(0,len(students_list)):
  print(f'Merhaba {(students_list[i])}')

  result = 0.0
  for j in range(0,len(grades)):
    #puan = print(float (input("Lütfen {}nuzu Giriniz: ".format(grades[j]))))
    puan= float (input("Lütfen {}nuzu Giriniz: ".format(grades[j])))
    
    k = float (percents[j])
    result = result + (puan * k)
    students[students_list[i]] [grades[j]] = puan

    j+=1
    
  passing_grade. append(result)
    


  students[students_list[i]] ["Başarı Notu"] = result

  print("Başarı Notunuz: ", result)


  i+=1

print("Başarı Notları: ",  passing_grade)

passing_grade.sort(reverse=True)

print("Başarı Notları Sıralı: ",passing_grade) 

print(students)


import pandas as pd
df = pd.DataFrame(students)
#print(df.T)
df_T= df.T
#print(df_T)
df_T.drop("Yaş", axis = 1, inplace = True)

df_T.sort_values('Başarı Notu',ascending=False)